#!/usr/bin/env python3
"""Build the self-contained Artifact bundle from the canonical source.

`index.html` is the source of truth. It links web fonts from the Google
Fonts CDN, which is fine for a normal web host or GitHub Pages. Some
targets, though, forbid external requests entirely — most notably a
Claude Artifact's strict Content-Security-Policy, or fully offline use.
For those, this script produces `dist/artifact.html`:

  * the outer <!doctype>/<html>/<head>/<body> wrapper is stripped
    (the Artifact runtime supplies its own), and
  * the CDN font <link> is replaced by @font-face rules whose sources
    are the fonts inlined as base64 data URIs (see vendor/fonts.embedded.css).

The vendored fonts (Fraunces, Inter, IBM Plex Mono) are all licensed
under the SIL Open Font License 1.1, which permits this embedding and
redistribution. See README.md for attribution.

Usage:
    python3 build.py            # regenerate dist/artifact.html

The build is deterministic and offline: it only reads local files.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE / "index.html"
FONTS = HERE / "vendor" / "fonts.embedded.css"
OUT = HERE / "dist" / "artifact.html"

TITLE = "Field Journal — Personalized Puppy Training"


def extract(pattern: str, text: str, what: str) -> str:
    match = re.search(pattern, text, re.S)
    if not match:
        sys.exit(f"build: could not find {what} in {SOURCE.name}")
    return match.group(1)


def main() -> None:
    for path in (SOURCE, FONTS):
        if not path.exists():
            sys.exit(f"build: missing required file {path}")

    src = SOURCE.read_text(encoding="utf-8")
    fonts = FONTS.read_text(encoding="utf-8").strip()

    # The page's own <style> block and the <body> content are all the
    # Artifact runtime needs; it wraps them in its own document skeleton.
    style = extract(r"<style>(.*?)</style>", src, "the <style> block")
    body = extract(r"<body>(.*)</body>", src, "the <body> content").strip()

    bundle = "\n".join(
        [
            f"<title>{TITLE}</title>",
            "<style>",
            "/* Fonts embedded as data URIs — the Artifact CSP blocks the Google Fonts CDN. */",
            "/* Generated by build.py from index.html + vendor/fonts.embedded.css — do not hand-edit. */",
            fonts,
            style,
            "</style>",
            body,
            "",
        ]
    )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(bundle, encoding="utf-8")

    # Sanity checks: the bundle must not leak wrapper tags or CDN links.
    leaks = [t for t in ("<!doctype", "<html", "<head>", "<body>", "fonts.googleapis") if t in bundle.lower()]
    if leaks:
        sys.exit(f"build: unexpected content in output: {', '.join(leaks)}")

    kb = len(bundle.encode("utf-8")) / 1024
    print(f"build: wrote {OUT.relative_to(HERE)} ({kb:.0f} KB, {bundle.count('@font-face')} fonts embedded)")


if __name__ == "__main__":
    main()
